In [3]:
import numpy as np

In [5]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
np.random.rand(2,3)

array([[0.26105089, 0.57947917, 0.28761453],
       [0.2722    , 0.77781625, 0.80700748]])

In [7]:
np.random.randint(5,size=(2,3))

array([[1, 3, 0],
       [4, 1, 4]])

In [8]:
np.fromfunction(lambda i,j:i+j,(3,3))

array([[0., 1., 2.],
       [1., 2., 3.],
       [2., 3., 4.]])

In [9]:
a = np.array([10,20,30])
b = np.arange(1,4)
a,b

(array([10, 20, 30]), array([1, 2, 3]))

In [10]:
a+b

array([11, 22, 33])

In [11]:
a-b

array([ 9, 18, 27])

In [12]:
a*b

array([10, 40, 90])

In [13]:
a/b

array([10., 10., 10.])

In [14]:
np.power(b,3)

array([ 1,  8, 27], dtype=int32)

In [17]:
c = np.vstack((a,b))
c

array([[10, 20, 30],
       [ 1,  2,  3]])

In [16]:
np.hstack((a,b))

array([10, 20, 30,  1,  2,  3])

In [18]:
c.ravel()

array([10, 20, 30,  1,  2,  3])

In [19]:
np.hsplit(c,3)

[array([[10],
        [ 1]]), array([[20],
        [ 2]]), array([[30],
        [ 3]])]

In [20]:
np.vsplit(c,2)

[array([[10, 20, 30]]), array([[1, 2, 3]])]

In [22]:
np.max(c)

30

In [23]:
np.max(c,axis=0)

array([10, 20, 30])

In [24]:
np.max(c,axis=1)

array([30,  3])

In [25]:
np.argmax(c,axis=0)

array([0, 0, 0], dtype=int64)

In [26]:
np.argmax(c,axis=1)

array([2, 2], dtype=int64)

In [27]:
np.median(c,axis=0)

array([ 5.5, 11. , 16.5])

In [28]:
np.mean(c,axis=0)

array([ 5.5, 11. , 16.5])

In [29]:
np.average(c,axis=0)

array([ 5.5, 11. , 16.5])

In [30]:
np.var(c,axis=0)

array([ 20.25,  81.  , 182.25])

In [32]:
np.std(c,axis=0)

array([ 4.5,  9. , 13.5])

In [33]:
np.diag(1+np.arange(4),k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])