In [2]:
import pandas as pd

In [3]:
import numpy as np

In [39]:
pd.__version__

'0.23.0'

## 创建Series
语法：s = pd.Series(data,index),有多种方法进行创建，常用从列表创建、从Ndarray创建、从字典创建

In [5]:
a1 = [0,1,2,3,4]
s1 = pd.Series(a1)
s1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [6]:
a2 = np.arange(5)
s2 = pd.Series(a2)
s2

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [7]:
a3 = np.random.random(5)
index = np.arange(5)
s3 = pd.Series(a3,index=index)
s3

0    0.211400
1    0.469024
2    0.861126
3    0.637314
4    0.058884
dtype: float64

从字典创建Series

In [8]:
a4 = {'a':1,'b':2,'c':3}
s4 = pd.Series(a4)
s4

a    1
b    2
c    3
dtype: int64

#### Series基本操作

修改Series索引

In [12]:
print(s1)
s1.index=('a','b','c','d','e')
s1

0    0
1    1
2    2
3    3
4    4
dtype: int64


a    0
b    1
c    2
d    3
e    4
dtype: int64

拼接

In [15]:
print(s1,s2)
s5 = s1.append(s2)
s5

a    0
b    1
c    2
d    3
e    4
dtype: int64 0    0
1    1
2    2
3    3
4    4
dtype: int32


a    0
b    1
c    2
d    3
e    4
0    0
1    1
2    2
3    3
4    4
dtype: int64

按指定索引删除元素

In [18]:
print(s5)
s5 = s5.drop(0)
print(s5)

a    0
b    1
c    2
d    3
0    0
1    1
2    2
3    3
4    4
dtype: int64
a    0
b    1
c    2
d    3
1    1
2    2
3    3
4    4
dtype: int64


修改指定索引元素

In [19]:
print(s5)
s5['d'] = 6
s5

a    0
b    1
c    2
d    3
1    1
2    2
3    3
4    4
dtype: int64


a    0
b    1
c    2
d    6
1    1
2    2
3    3
4    4
dtype: int64

In [21]:
s5['c']

2

#### Series运算

In [25]:
print(s1,s2)
s6 = s1.append(s2)
print(s6)
s7 = s1.add(s2)
print(s7)
s8 = s6.add(s6)
print(s8)
s9 = s6.add(s1)
print(s9)

a    0
b    1
c    2
d    3
e    4
dtype: int64 0    0
1    1
2    2
3    3
4    4
dtype: int32
a    0
b    1
c    2
d    3
e    4
0    0
1    1
2    2
3    3
4    4
dtype: int64
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
dtype: float64
a    0
b    2
c    4
d    6
e    8
0    0
1    2
2    4
3    6
4    8
dtype: int64
a    0.0
b    2.0
c    4.0
d    6.0
e    8.0
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
dtype: float64


C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:7435: RuntimeWarning: '<' not supported between instances of 'int' and 'str', sort order is undefined for incomparable objects
  return_indexers=True)


In [27]:
print(s8,s6)
s8.sub(s6)

a    0
b    2
c    4
d    6
e    8
0    0
1    2
2    4
3    6
4    8
dtype: int64 a    0
b    1
c    2
d    3
e    4
0    0
1    1
2    2
3    3
4    4
dtype: int64


a    0
b    1
c    2
d    3
e    4
0    0
1    1
2    2
3    3
4    4
dtype: int64

In [32]:
print(s1,s6)
s1.mul(s6)
s6.div(s1)

a    0
b    1
c    2
d    3
e    4
dtype: int64 a    0
b    1
c    2
d    3
e    4
0    0
1    1
2    2
3    3
4    4
dtype: int64


C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:7435: RuntimeWarning: '<' not supported between instances of 'str' and 'int', sort order is undefined for incomparable objects
  return_indexers=True)
C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\generic.py:7435: RuntimeWarning: '<' not supported between instances of 'int' and 'str', sort order is undefined for incomparable objects
  return_indexers=True)


a    NaN
b    1.0
c    1.0
d    1.0
e    1.0
0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
dtype: float64

In [38]:
print(s6)
print(s6.median())
print(s6.sum())
print(s6.max())
print(s6.min())

a    0
b    1
c    2
d    3
e    4
0    0
1    1
2    2
3    3
4    4
dtype: int64
2.0
20
4
0


## 创建DataFrame数据类型

In [45]:
dates = pd.date_range('today',periods=7)
print(dates)
num_arr = np.random.randn(7,4)
print(num_arr)
columns = ['A','B','C','D']
df1 = pd.DataFrame(num_arr,index=dates,columns=columns)
df1

DatetimeIndex(['2019-11-18 12:03:04.541918', '2019-11-19 12:03:04.541918',
               '2019-11-20 12:03:04.541918', '2019-11-21 12:03:04.541918',
               '2019-11-22 12:03:04.541918', '2019-11-23 12:03:04.541918',
               '2019-11-24 12:03:04.541918'],
              dtype='datetime64[ns]', freq='D')
[[ 0.16654646  0.35481733 -0.53261403 -2.01549241]
 [ 2.27814322 -1.51850649 -0.78384163  1.33545886]
 [ 1.19981061 -1.6555828  -1.36017129 -1.8811454 ]
 [-1.45464948 -0.69004842  0.68304075 -0.97083295]
 [-0.86887368 -0.50345717  0.0491316  -0.49725489]
 [ 0.43391453  0.44973518 -0.8153158  -1.13906842]
 [ 0.89407661 -1.07303649 -0.76267608  0.98914604]]


A         B         C         D
2019-11-18 12:03:04.541918  0.166546  0.354817 -0.532614 -2.015492
2019-11-19 12:03:04.541918  2.278143 -1.518506 -0.783842  1.335459
2019-11-20 12:03:04.541918  1.199811 -1.655583 -1.360171 -1.881145
2019-11-21 12:03:04.541918 -1.454649 -0.690048  0.683041 -0.970833
2019-11-22 12:03:04.541918 -0.868874 -0.503457  0.049132 -0.497255
2019-11-23 12:03:04.541918  0.433915  0.449735 -0.815316 -1.139068
2019-11-24 12:03:04.541918  0.894077 -1.073036 -0.762676  0.989146

In [86]:
data = {'animal':['cat','cat','snake','dog'],'age':[2.5,3,4,2],'visits':[1,2,3,1],'priority':['yes','no','yes','no']}
labels = ['a','b','c','d']
df2 = pd.DataFrame(data,index=labels)
print(df2)
print(df2.dtypes)
print(df1.dtypes)

NameError: name 'NaN' is not defined

#### DataFrame基本操作

In [104]:
print(df2.head())
print(df2.tail(2))
print(df2.index)
print(df2.columns)
print(df2.values)
print(df2.describe())
print(df2.shape)
df2

  animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       2       no
c  snake  4.0       3      yes
d    dog  2.0       1       no
  animal  age  visits priority
c  snake  4.0       3      yes
d    dog  2.0       1       no
Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['animal', 'age', 'visits', 'priority'], dtype='object')
[['cat' 2.5 1 'yes']
 ['cat' 3.0 2 'no']
 ['snake' 4.0 3 'yes']
 ['dog' 2.0 1 'no']]
            age    visits
count  4.000000  4.000000
mean   2.875000  1.750000
std    0.853913  0.957427
min    2.000000  1.000000
25%    2.375000  1.000000
50%    2.750000  1.500000
75%    3.250000  2.250000
max    4.000000  3.000000
(4, 4)


animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       2       no
c  snake  4.0       3      yes
d    dog  2.0       1       no

In [64]:
df2.T

a    b      c    d
animal    cat  cat  snake  dog
age       2.5    3      4    2
visits      1    2      3    1
priority  yes   no    yes   no

In [66]:
df2.sort_values(by='age')

animal  age  visits priority
d    dog  2.0       1       no
a    cat  2.5       1      yes
b    cat  3.0       2       no
c  snake  4.0       3      yes

In [67]:
df2[1:3]

animal  age  visits priority
b    cat  3.0       2       no
c  snake  4.0       3      yes

In [68]:
df2['age']

a    2.5
b    3.0
c    4.0
d    2.0
Name: age, dtype: float64

In [69]:
df2.age

a    2.5
b    3.0
c    4.0
d    2.0
Name: age, dtype: float64

In [73]:
df2[['age','visits']]

age  visits
a  2.5       1
b  3.0       2
c  4.0       3
d  2.0       1

In [105]:
df2.iloc[:,1:3]

age  visits
a  2.5       1
b  3.0       2
c  4.0       3
d  2.0       1

In [75]:
df3 = df2.copy()
df3

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       2       no
c  snake  4.0       3      yes
d    dog  2.0       1       no

In [77]:
df3.isnull()

animal    age  visits  priority
a   False  False   False     False
b   False  False   False     False
c   False  False   False     False
d   False  False   False     False

In [78]:
num = pd.Series([0,1,2,3],index=df3.index)
df3['No.'] = num
df3

animal  age  visits priority  No.
a    cat  2.5       1      yes    0
b    cat  3.0       2       no    1
c  snake  4.0       3      yes    2
d    dog  2.0       1       no    3

In [88]:
df3.iat[2,1] = np.nan
df3

animal  age  visits priority  No.
a    cat  2.5       1      yes    0
b    cat  NaN       2       no    1
c  snake  NaN       3      yes    2
d    dog  2.0       1       no    3

In [89]:
df3.loc['b','age'] = np.nan
df3

animal  age  visits priority  No.
a    cat  2.5       1      yes    0
b    cat  NaN       2       no    1
c  snake  NaN       3      yes    2
d    dog  2.0       1       no    3

In [90]:
df3.mean()

age       2.25
visits    1.75
No.       1.50
dtype: float64

In [91]:
df3['visits'].sum()

7

In [93]:
df3.fillna(value=3)

animal  age  visits priority  No.
a    cat  2.5       1      yes    0
b    cat  3.0       2       no    1
c  snake  3.0       3      yes    2
d    dog  2.0       1       no    3

In [96]:
df3.dropna(how='any')

animal  age  visits priority  No.
a    cat  2.5       1      yes    0
d    dog  2.0       1       no    3

In [99]:
pd.merge(df2,df3,on='age')

animal_x  age  visits_x priority_x animal_y  visits_y priority_y  No.
0      cat  2.5         1        yes      cat         1        yes    0
1      dog  2.0         1         no      dog         1         no    3

In [100]:
df3.to_csv('animal.csv')

In [101]:
df_animal = pd.read_csv('animal.csv')
df_animal

Unnamed: 0 animal  age  visits priority  No.
0          a    cat  2.5       1      yes    0
1          b    cat  NaN       2       no    1
2          c  snake  NaN       3      yes    2
3          d    dog  2.0       1       no    3

In [102]:
df3.to_excel('animal.xlsx',sheet_name='Sheet1')
pd.read_excel('animal.xlsx','Sheet1',index_col=None,na_values=['NA'])

animal  age  visits priority  No.
a    cat  2.5       1      yes    0
b    cat  NaN       2       no    1
c  snake  NaN       3      yes    2
d    dog  2.0       1       no    3

## 时间序列索引

建立一个以2018年每一天为索引，值为随机数的Series

In [107]:
dti = pd.date_range(start='2019-01-01',end='2019-12-31',freq='D')
s = pd.Series(np.random.rand(365),index=dti)
s

2019-01-01    0.683388
2019-01-02    0.795123
2019-01-03    0.000716
2019-01-04    0.114925
2019-01-05    0.241610
2019-01-06    0.644272
2019-01-07    0.958741
2019-01-08    0.905133
2019-01-09    0.261795
2019-01-10    0.988572
2019-01-11    0.400349
2019-01-12    0.191759
2019-01-13    0.184462
2019-01-14    0.367120
2019-01-15    0.264654
2019-01-16    0.223106
2019-01-17    0.089375
2019-01-18    0.056505
2019-01-19    0.581225
2019-01-20    0.868409
2019-01-21    0.539032
2019-01-22    0.002479
2019-01-23    0.274321
2019-01-24    0.623962
2019-01-25    0.585014
2019-01-26    0.580684
2019-01-27    0.960170
2019-01-28    0.931593
2019-01-29    0.516867
2019-01-30    0.045396
                ...   
2019-12-02    0.488664
2019-12-03    0.030224
2019-12-04    0.239345
2019-12-05    0.391807
2019-12-06    0.782205
2019-12-07    0.133045
2019-12-08    0.107535
2019-12-09    0.352459
2019-12-10    0.293488
2019-12-11    0.492015
2019-12-12    0.255215
2019-12-13    0.970903
2019-12-14 

## Series多重索引

In [111]:
letters = list('ABCD')
numbers = list(range(5))
doubleindex = pd.MultiIndex.from_product([letters,numbers])
s1 = pd.Series(np.random.rand(20),index=doubleindex)
s1

A  0    0.382171
   1    0.040837
   2    0.701305
   3    0.751902
   4    0.438332
B  0    0.794920
   1    0.046912
   2    0.076357
   3    0.574460
   4    0.278074
C  0    0.911305
   1    0.668048
   2    0.682977
   3    0.756612
   4    0.283196
D  0    0.178344
   1    0.444496
   2    0.968824
   3    0.635287
   4    0.708179
dtype: float64